spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/secondhandplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

#开启驼峰命名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    path: D:/upload/images/  # 本地基础存储路径
    access-path: /images/**  # 前端访问路径映射
